### ISSUE TITLE
Research TMDB API

### ISSUE THREAD

**Issue by Jen-Lopez** [Jen-Lopez/movie-review-app#1]
https://www.themoviedb.org/ 

What endpoints do we need to use?

**Comment by lucasortizny** [comment]
Authentication for the TMDB endpoints will be through API key (not feasible for scaling upwards). GET requests to /movie/ will be the primary. maybe GET /movie/<id>/similar for any recommendations. We can review more of the endpoints, but we are only making GET requests on movies. For the user to search, a GET request on /search/ is going to be the key. https://developers.themoviedb.org/3/movies/get-movie-details
AND
https://developers.themoviedb.org/3/search/search-movies


We can tackle further categorization like genres and stuff later. Primary focus will be on searching specific movies via a search bar.
